# Generated by Django 2.0.5 on 2019-09-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost', models.FloatField()),
                ('product_color', models.CharField(max_length=100)),
                ('product_class', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.BigIntegerField()),
                ('customer_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
